2016-04-28 16:43:45,192 - streamparse.storm.component - ERROR - Exception in WordCounter.run()
Traceback (most recent call last):
  File "/opt/py27environment/lib/python2.7/site-packages/streamparse/storm/component.py", line 487, in run
    self.initialize(storm_conf, context)
  File "bolts/wordcount.py", line 21, in initialize
    count INT     NOT NULL);""")
ProgrammingError: relation "tweetwordcount" already exists

